# -*- coding: utf-8 -*-
"""task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEU2v8Wff4bTGFzAAl8SWdq6q_qbpQ_q
"""

input = open('input3.txt','r')
output = open('output3.txt','w')

N , M = tuple(map(int,input.readline().split()))

par = [int(i) for i in range(N+1)]
siz = [1]*(N+1)

def find(r):
	if par[r]==r: return r
	return find(par[r])

def union(a,b):
    u = find(a)
    v = find(b)
    if u==v: return
    if siz[u] < siz [v]:
        u ,v = v , u
    par[v] = u
    siz[u] += siz[v]
    for i in range(len(par)):
        if find(i) == u:
            siz[i] = siz[u]

for _ in range(M):
      a , b = tuple(map(int,input.readline().split()))
      union(a,b)
      output.write(f'{siz[a]}\n')



input.close()
output.close()